name: Daily Auto Commit

on:
  schedule:
    - cron: '0 5 * * *'   # Daily run (UTC time)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Auto commit on $(date)" >> data.txt

      - name: Commit and Push
        run: |
          git config user.name "Shubham"
          git config user.email "your-github-email@example.com"
          git add .
          git commit -m "Daily auto commit"
          git push
